### ISSUE TITLE
你的程序能运行成功吗？

### ISSUE THREAD

**Issue by longfeizheng** [duydcoco/springboot-demo#1]
运行 test MybatisAutoConfiguration报错

**Comment by longfeizheng** [comment]
( ╯□╰ )
//    @Bean
//    @ConditionalOnMissingBean
//    public SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory sqlSessionFactory) {
//        return new SqlSessionTemplate(sqlSessionFactor);
//    }
把这个注释掉成功运行

**Comment by duydcoco** [comment]
对,把那个注释掉,最近比较忙,不好意思...

**Comment by longfeizheng** [comment]
再麻烦一下 你的程序出现过这种问题吗？
`Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'mapperHelper' of bean class [org.mybatis.spring.mapper.MapperFactoryBean]: Bean property 'mapperHelper' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?`

**Comment by duydcoco** [comment]
没有，但是看异常是通用mapper出的问题，你检查下你的set方法跟字段是不是按照 驼峰的那种命名。Ps:通用mapper只适合单表的
